apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spring-boot-server-tutorialsonline-7cvr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-boot-server-tutorialsonline-7cvr
    app.kubernetes.io/part-of: tutorialsonline-3
  name: spring-boot-server-tutorialsonline-7cvr
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: spring-boot-server-tutorialsonline-7cvr
status:
  loadBalancer: {}
