apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spring-boot-server-tutorialsonline-7cvr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-boot-server-tutorialsonline-7cvr
    app.kubernetes.io/part-of: tutorialsonline-3
  name: spring-boot-server-tutorinal7
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: spring-boot-server-tutorialsonline-7cvr
    weight: null
status: {}
